"""add UniqueConstraint 'email'

Revision ID: 92211115fdc2
Revises: ffad783488ec
Create Date: 2024-09-06 12:18:37.163628

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "92211115fdc2"
down_revision = "ffad783488ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_unique_constraint("email_unique_constraint", ["email"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_constraint("email_unique_constraint", type_="unique")

    # ### end Alembic commands ###
